// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljiyaiclwdfyjoalzyzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqaXlhaWNsd2RmeWpvYWx6eXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMDQyMDQsImV4cCI6MjA2NjY4MDIwNH0.iWyVPn5Sv6C4ONTDslomIw24Fp9NYx2kNHsD9DmAur0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);